### ISSUE TITLE
Can't build with rustc 1.54

### ISSUE THREAD

**Issue by fzzr-** [fornwall/rust-script#34]
Can't build on macOS with: 
- rustc 1.56.0-nightly (6d64f7f69 2021-08-19)
- rustc 1.54.0 (a178d0322 2021-07-26)

__macOS__: 11.5.2 (20G95)

```
cargo install rust-script
...
  Installing rust-script v0.16.0
   Compiling rust-script v0.16.0
error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-script-0.16.0/src/main.rs:125:18
    |
125 |                 .multiple(true)
    |                  ^^^^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-script-0.16.0/src/main.rs:168:18
    |
168 |                 .multiple(true)
    |                  ^^^^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-script-0.16.0/src/main.rs:176:18
    |
176 |                 .multiple(true)
    |                  ^^^^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-script-0.16.0/src/main.rs:184:18
    |
184 |                 .multiple(true)
    |                  ^^^^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-script-0.16.0/src/main.rs:197:18
    |
197 |                 .multiple(true)
    |                  ^^^^^^^^ method not found in `Arg<'_>`

For more information about this error, try `rustc --explain E0599`.


rustc -V            
rustc 1.56.0-nightly (6d64f7f69 2021-08-19)
```

**Comment by fornwall** [comment]
Thanks for reporting!

Should be fixed by the just released 0.17.0 version - let me know otherwise!
