### PR TITLE
Fix unresolved import

### PR DESCRIPTION
**Pull request by tottoto**
Fixes unresolved import introduced in #91, which occurs outside unix.

### CODE REVIEW

**Comment by fornwall** [comment]
That was fast :) - thanks!
